- name: ensure dhcpd is enabled
  debug:
    msg: "enabling dhcpd"
  notify: enable dhcpd

- name: copy dhcpd.conf
  tags: openbsd-dhcpd
  template:
    src: "{{ openbsd_dhcpd_conf_src }}"
    dest: "{{ openbsd_dhcpd_conf_dest }}"
    mode: "0644"
    owner: "root"
    group: "wheel"
    backup: "yes"
  notify: restart dhcpd
